"""neat-python integration: config rendering, founding structure, conversion."""

import os
import random
import tempfile

import torch
from helpers import neat_population, random_fitness, reachable_all

from evogrokking import datasets
from evogrokking.models import build_model
from evogrokking.neat_arch import CONFIG_TEMPLATE, to_genome, write_config


# --------------------------------------------------------------------------
# The config template
# --------------------------------------------------------------------------
def test_config_template_renders_with_every_placeholder_filled():
    # The template is str.format-ed, so a stray unescaped brace anywhere in it
    # would raise at render time -- catch that here rather than mid-search.
    path = write_config(
        os.path.join(tempfile.mkdtemp(), "neat.ini"),
        pop_size=7, n_inputs=11, n_outputs=3, n_hidden=5,
    )
    text = open(path).read()
    assert "{" not in text and "}" not in text, "unsubstituted placeholder left behind"
    assert "pop_size              = 7" in text
    assert "num_inputs            = 11" in text
    assert "num_hidden            = 5" in text


def test_config_template_is_a_file_not_an_inline_string():
    assert CONFIG_TEMPLATE.exists() and CONFIG_TEMPLATE.suffix == ".config"
    assert "[NEAT]" in CONFIG_TEMPLATE.read_text()


def test_template_authoring_notes_are_stripped_from_the_output():
    # ``##`` lines document the template for whoever edits it -- including the
    # brace-doubling rule -- and must not leak into the generated run record.
    assert any(
        line.startswith("##") for line in CONFIG_TEMPLATE.read_text().splitlines()
    ), "expected ## authoring notes in the template"

    path = write_config(
        os.path.join(tempfile.mkdtemp(), "neat.ini"),
        pop_size=4, n_inputs=6, n_outputs=2, n_hidden=3,
    )
    rendered = open(path).read()
    assert not any(line.startswith("##") for line in rendered.splitlines())
    assert rendered.startswith("# Generated by evogrokking")
    assert rendered.endswith("\n") and not rendered.endswith("\n\n")


def test_cli_knobs_reach_the_rendered_config():
    path = write_config(
        os.path.join(tempfile.mkdtemp(), "neat.ini"),
        pop_size=4, n_inputs=6, n_outputs=2, n_hidden=3,
        compatibility_threshold=0.33, node_delete_prob=0.42,
        initial_connection="full_nodirect",
    )
    text = open(path).read()
    assert "compatibility_threshold = 0.33" in text
    assert "node_delete_prob      = 0.42" in text
    assert "initial_connection    = full_nodirect" in text


# --------------------------------------------------------------------------
# The founding population
# --------------------------------------------------------------------------
def test_founding_population_shares_its_hidden_neurons():
    # neat-python normally hands each founding genome its OWN hidden keys, which
    # makes the whole population mutually non-homologous -- every genome its own
    # species, crossover reduced to copying.  ArchGenome fixes that.
    pop, cfg = neat_population(pop_size=10, n_inputs=20, n_hidden=8)
    genomes = list(pop.population.values())
    keys = [sorted(k for k in g.nodes if k >= 3) for g in genomes]
    assert all(k == keys[0] for k in keys), "founding genomes must share hidden keys"
    assert genomes[0].distance(genomes[1], cfg.genome_config) == 0.0
    assert len(pop.species.species) == 1  # ...so they start as one species


def test_weights_and_biases_are_not_evolved():
    # They come from gradient descent, so their genes stay pinned and contribute
    # nothing to the genomic distance.
    pop, _ = neat_population(pop_size=6, n_inputs=8, n_hidden=4)
    genomes = list(pop.population.values())
    weights = {c.weight for g in genomes for c in g.connections.values()}
    biases = {n.bias for g in genomes for n in g.nodes.values()}
    assert weights == {1.0}
    assert biases == {0.0}


# --------------------------------------------------------------------------
# Evolution and conversion
# --------------------------------------------------------------------------
def _config_with(**kw):
    import neat

    from evogrokking.neat_arch import ArchGenome

    path = write_config(os.path.join(tempfile.mkdtemp(), "neat.ini"), **kw)
    return neat.Config(
        ArchGenome, neat.DefaultReproduction, neat.DefaultSpeciesSet,
        neat.DefaultStagnation, path,
    )


def test_mutation_rounds_scale_the_structural_step():
    # neat-python changes at most one gene of each kind per genome per
    # generation, which is a negligible step for a dense genome.  Repeating the
    # operators must move proportionally more genes.  Exercised directly on
    # `mutate` so the measurement is of the operator, not of selection.
    import random as _random

    def churn(rounds):
        cfg = _config_with(
            pop_size=4, n_inputs=60, n_outputs=5, n_hidden=12,
            structural_mutation_rounds=rounds,
        )
        _random.seed(0)
        pop = __import__("neat").Population(cfg, seed=0)
        genome = next(iter(pop.population.values()))
        before = len(genome.connections)
        genome.mutate(cfg.genome_config)
        return abs(before - len(genome.connections))

    one, many = churn(1), churn(60)
    # A single round touches at most a handful of genes (each add-node adds two
    # connection genes plus disables one); 60 rounds must move far more.
    assert one <= 6, f"a single round moved {one} connections -- expected a handful"
    assert many > 8 * max(one, 1), f"60 rounds moved only {many} vs {one} for one"


def test_mutation_rounds_reach_the_genome_config():
    import neat

    from evogrokking.neat_arch import ArchGenome

    path = write_config(
        os.path.join(tempfile.mkdtemp(), "neat.ini"),
        pop_size=4, n_inputs=6, n_outputs=2, n_hidden=3,
        structural_mutation_rounds=17,
    )
    cfg = neat.Config(
        ArchGenome, neat.DefaultReproduction, neat.DefaultSpeciesSet,
        neat.DefaultStagnation, path,
    )
    assert cfg.genome_config.structural_mutation_rounds == 17
    # It is ours, not neat-python's: it must not leak into the library's params.
    assert "structural_mutation_rounds" not in [p.name for p in cfg.genome_config._params]


def test_partial_initial_connectivity_diversifies_the_founders():
    # Fully wired founders are byte-identical, so generation 0 trains the same
    # network pop_size times.  A fraction below 1 gives each its own subset.
    import neat

    from evogrokking.neat_arch import ArchGenome

    def founders(fraction):
        path = write_config(
            os.path.join(tempfile.mkdtemp(), "neat.ini"),
            pop_size=8, n_inputs=40, n_outputs=5, n_hidden=10,
            initial_connection_fraction=fraction,
        )
        cfg = neat.Config(
            ArchGenome, neat.DefaultReproduction, neat.DefaultSpeciesSet,
            neat.DefaultStagnation, path,
        )
        pop = neat.Population(cfg, seed=0)
        genomes = list(pop.population.values())
        distances = {genomes[0].distance(g, cfg.genome_config) for g in genomes[1:]}
        return genomes, distances, len(pop.species.species)

    _full, full_d, full_species = founders(1.0)
    part, part_d, part_species = founders(0.5)

    assert full_d == {0.0} and full_species == 1  # all clones, one species
    assert min(part_d) > 0.0 and part_species > 1  # genuinely diverse
    # ...and sparser: roughly half the wiring.
    full_conns = len(_full[0].connections)
    assert 0.4 * full_conns < len(part[0].connections) < 0.6 * full_conns


def test_initial_connection_fraction_is_validated():
    kw = dict(pop_size=4, n_inputs=6, n_outputs=2, n_hidden=3)
    for bad in (0.0, -0.5, 1.5):
        try:
            write_config(os.path.join(tempfile.mkdtemp(), "n.ini"),
                         initial_connection_fraction=bad, **kw)
        except ValueError:
            continue
        raise AssertionError(f"expected ValueError for fraction={bad}")


def test_neat_population_evolves_and_converts_to_genomes():
    pop, _ = neat_population(pop_size=10)
    pop.run(random_fitness(random.Random(0)), 5)
    assert pop.best_genome is not None

    g = to_genome(pop.best_genome, 6, 3)
    ids = g.node_ids()
    for c in g.conns:
        assert c.src in ids and c.dst in ids
    for node in ids:
        assert node not in reachable_all(g.conns, node)  # still a DAG
    for n in g.nodes:
        assert n.activation in ("relu", "gelu", "tanh", "silu")


def test_evolution_can_grow_past_one_hidden_layer():
    # The dense start is a single hidden layer; add-node mutations must be able
    # to deepen it, otherwise the search could only ever prune width.
    from evogrokking.models import _levels

    pop, _ = neat_population(pop_size=16, n_inputs=20, n_outputs=3, n_hidden=8, seed=1)

    def hidden_depth(neat_genome):
        g = to_genome(neat_genome, 20, 3)
        return len(_levels(g.conns, g.node_ids(), set(g.input_ids()))) - 2

    assert {hidden_depth(g) for g in pop.population.values()} == {1}  # dense start
    pop.run(random_fitness(random.Random(0)), 10)
    assert max(hidden_depth(g) for g in pop.population.values()) > 1


def test_neat_genome_builds_a_trainable_model():
    pop, _ = neat_population(pop_size=6, n_inputs=20, n_outputs=3, seed=5)
    pop.run(random_fitness(random.Random(2)), 3)

    spec = datasets.DatasetSpec("t", "image", input_dim=20, num_classes=3)
    for ng in pop.population.values():
        model = build_model(to_genome(ng, 20, 3), spec)
        assert model(torch.randn(4, 20)).shape == (4, 3)
